### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gabrielnhn** [Ay-De/Kivy_Python_Camera_Demo#7]
Hi there Mr. Deliktas,
I'm developing a Kivy/CV2 project myself. I've found you in this discussion (https://github.com/opencv/opencv/pull/19597) and it got me to your project, which works great.

In my project, I'm having difficulties on getting acces to the cv2.videoCapture() on android, all the reads return False. But your app works fine on my same phone.

What could it be, the fact that you use your own `opencv` recipe, instead of the default one?
Thanks in advance.

**Comment by Ay-De** [comment]
The reason that i used my own recipe is, that the default one uses an old opencv build. The android specific fixes have only now been added in the newer opencv releases. I changed the build version of opencv to 4.5.5, which is working on android.

Have you added the cv2.CAP_ANDROID flag?

**Comment by gabrielnhn** [comment]
Hey there, just want to thank you for the help.
My problem was happenning mostly because of Android's NDK version and NDK API version as well. 
Only realised it by checking your `buildozer.spec` file, so thank you very much.

**Comment by jamalkhanjay** [comment]
Hey...! @Ay-De I have an issue of not opening the camera in my android phone. When I click on my Camera Button the App directly crashes. 
Idk about Android's NDK  and NDK API versions, that which version I put in it. That it works. 
please help
