### ISSUE TITLE
TypeError: get_site_packages_dir() missing 1 required positional argument: 'arch'

### ISSUE THREAD

**Issue by gone-still** [Ay-De/Kivy_Python_Camera_Demo#8]
Currently, building and deploying the app with buildozer is giving me this error. The error is located in `line 64, __init__.py` of the OpenCV recipe. Building with OpenCV 4.5.5.

**Comment by Ay-De** [comment]
Sorry for the late reply. i will push an update later to fix that bug.

**Comment by gone-still** [comment]
Thanks!
