### ISSUE TITLE
issues on android opencv kivy

### ISSUE THREAD

**Issue by kikyrizkianunkyw** [Ay-De/Kivy_Python_Camera_Demo#9]
Hello ay de , i am kiky. so i have my kivy opencv face recognition codes to access on android. and i already build the app into .apk with buildozer, but sadly the app wont app. Can you help me with it please?, here is my email in case you need answer me. kikyrizkianunkywofficial@gmail.com

**Comment by Ay-De** [comment]
have you checked the logcat on android? Does the app run on Windows?
